// Copyright (c) Efficient Go Authors
// Licensed under the Apache License 2.0.

package main

import (
	"fmt"
	"os"
	"runtime"
)

var m = &runtime.MemStats{}

func _printHeapUsageAndWait() {
	runtime.GC()
	runtime.ReadMemStats(m)
	fmt.Println(m.HeapAlloc)
	fmt.Scanln() // wait for Enter Key
}

// Interactive example of influence of access patterns and GC when using a memory block.
// Read more in "Efficient Go"; Example 5-5, Example 5-6.

/*
# command-line-arguments
./slice.go:25:13: inlining call to fmt.Println
./slice.go:26:12: inlining call to fmt.Scanln
./slice.go:25:15: m.HeapAlloc escapes to heap
./slice.go:25:13: []interface {}{...} does not escape
./slice.go:11:11: make([]byte, size) escapes to heap
<autogenerated>:1: leaking param content: .this
*/
func main() {
	fmt.Println("PID", os.Getpid())
	b := make([]byte, 600*1024*1024) // 600 MB

	// If we would pause the program now `cat /proc/<PID>/smaps | grep -A22 7ff358296000-7ff362d38000 | grep Rss`

	_printHeapUsageAndWait()

	b[5000] = 3
	_printHeapUsageAndWait()

	b[100000] = 2

	_printHeapUsageAndWait()

	b[104000] = 1

	_printHeapUsageAndWait()

	for i := range b {
		b[i] = 3
	}

	_printHeapUsageAndWait()

	b[0] = 1
	b = nil
	_printHeapUsageAndWait()
	_printHeapUsageAndWait()

	b = make([]byte, 300*1024*1024) // 300 MB

	for i := range b {
		b[i] = 3
	}

	_printHeapUsageAndWait()
	runtime.KeepAlive(b)
	_printHeapUsageAndWait()
}

/*
		cat /proc/2077387/smaps | grep -A22 c000200000
	c000000000-c000200000 rw-p 00000000 00:00 0
	Size:               2048 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                 548 kB
	Pss:                 548 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:       548 kB
	Referenced:          548 kB
	Anonymous:           548 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    0
	VmFlags: rd wr mr mw me ac sd
	c000200000-c025800000 rw-p 00000000 00:00 0
	Size:             612352 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                   0 kB
	Pss:                   0 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:         0 kB
	Referenced:            0 kB
	Anonymous:             0 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    1
	VmFlags: rd wr mr mw me ac sd hg
	➜  ~ cat /proc/2077387/smaps | grep -A22 c000200000
	c000000000-c000200000 rw-p 00000000 00:00 0
	Size:               2048 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                 596 kB
	Pss:                 596 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:       596 kB
	Referenced:          596 kB
	Anonymous:           596 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    0
	VmFlags: rd wr mr mw me ac sd
	c000200000-c025800000 rw-p 00000000 00:00 0
	Size:             612352 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                   0 kB
	Pss:                   0 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:         0 kB
	Referenced:            0 kB
	Anonymous:             0 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    1
	VmFlags: rd wr mr mw me ac sd hg
	➜  ~ cat /proc/2077387/smaps | grep -A22 c000200000
	c000000000-c000200000 rw-p 00000000 00:00 0
	Size:               2048 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                 600 kB
	Pss:                 600 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:       600 kB
	Referenced:          600 kB
	Anonymous:           600 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    0
	VmFlags: rd wr mr mw me ac sd
	c000200000-c025800000 rw-p 00000000 00:00 0
	Size:             612352 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                   0 kB
	Pss:                   0 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:         0 kB
	Referenced:            0 kB
	Anonymous:             0 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    1
	VmFlags: rd wr mr mw me ac sd hg
	➜  ~ cat /proc/2077387/smaps | grep -A22 c000200000
	c000000000-c000200000 rw-p 00000000 00:00 0
	Size:               2048 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                 636 kB
	Pss:                 636 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:       636 kB
	Referenced:          636 kB
	Anonymous:           636 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    0
	VmFlags: rd wr mr mw me ac sd
	c000200000-c025800000 rw-p 00000000 00:00 0
	Size:             612352 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                   0 kB
	Pss:                   0 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:         0 kB
	Referenced:            0 kB
	Anonymous:             0 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    1
	VmFlags: rd wr mr mw me ac sd hg
	➜  ~ cat /proc/2077387/smaps | grep -A22 c000200000
	c000000000-c000200000 rw-p 00000000 00:00 0
	Size:               2048 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                1136 kB
	Pss:                1136 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:      1136 kB
	Referenced:         1136 kB
	Anonymous:          1136 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    0
	VmFlags: rd wr mr mw me ac sd
	c000200000-c025800000 rw-p 00000000 00:00 0
	Size:             612352 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:              612352 kB
	Pss:              612352 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:    612352 kB
	Referenced:       612352 kB
	Anonymous:        612352 kB
	LazyFree:              0 kB
	AnonHugePages:    612352 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    1
	VmFlags: rd wr mr mw me ac sd hg
	➜  ~ cat /proc/2077387/smaps | grep -A22 c000200000
	c000000000-c000200000 rw-p 00000000 00:00 0
	Size:               2048 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                1208 kB
	Pss:                1208 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:      1208 kB
	Referenced:         1208 kB
	Anonymous:          1208 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    0
	VmFlags: rd wr mr mw me ac sd
	c000200000-c025800000 rw-p 00000000 00:00 0
	Size:             612352 kB
	KernelPageSize:        4 kB
	MMUPageSize:           4 kB
	Rss:                   0 kB
	Pss:                   0 kB
	Shared_Clean:          0 kB
	Shared_Dirty:          0 kB
	Private_Clean:         0 kB
	Private_Dirty:         0 kB
	Referenced:            0 kB
	Anonymous:             0 kB
	LazyFree:              0 kB
	AnonHugePages:         0 kB
	ShmemPmdMapped:        0 kB
	FilePmdMapped:         0 kB
	Shared_Hugetlb:        0 kB
	Private_Hugetlb:       0 kB
	Swap:                  0 kB
	SwapPss:               0 kB
	Locked:                0 kB
	THPeligible:    1
	VmFlags: rd wr mr mw me ac sd hg

go run slice.go
PID 2077387
629312016

629317296

629317296

629317296

629317296

171696


VmRSS:	   21680 kB
➜  ~ cat /proc/2079522/status | grep VmRSS
VmRSS:	   22080 kB
➜  ~ cat /proc/2079522/status | grep VmRSS
VmRSS:	   22080 kB
➜  ~ cat /proc/2079522/status | grep VmRSS
VmRSS:	   22080 kB
➜  ~ cat /proc/2079522/status | grep VmRSS
VmRSS:	  636636 kB
➜  ~ cat /proc/2079522/status | grep VmRSS
VmRSS:	   22880 kB
 cat /proc/3290226/smaps | grep -A38 c000200000
c000000000-c000200000 rw-p 00000000 00:00 0
Size:               2048 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 508 kB
Pss:                 508 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       508 kB
Referenced:          508 kB
Anonymous:           508 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me ac sd
c000200000-c025800000 rw-p 00000000 00:00 0
Size:             612352 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    1
VmFlags: rd wr mr mw me ac sd hg
c025800000-c025c00000 rw-p 00000000 00:00 0
Size:               4096 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 120 kB
Pss:                 120 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       120 kB
Referenced:          120 kB
Anonymous:           120 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
➜  efficient-go git:(main) ✗ cat /proc/3290226/smaps | grep -A38 c000200000
c000000000-c000200000 rw-p 00000000 00:00 0
Size:               2048 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 544 kB
Pss:                 544 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       544 kB
Referenced:          544 kB
Anonymous:           544 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me ac sd
c000200000-c025800000 rw-p 00000000 00:00 0
Size:             612352 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    1
VmFlags: rd wr mr mw me ac sd hg
c025800000-c025c00000 rw-p 00000000 00:00 0
Size:               4096 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 120 kB
Pss:                 120 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       120 kB
Referenced:          120 kB
Anonymous:           120 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
➜  efficient-go git:(main) ✗ cat /proc/3290226/smaps | grep -A38 c000200000
c000000000-c000200000 rw-p 00000000 00:00 0
Size:               2048 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 552 kB
Pss:                 552 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       552 kB
Referenced:          552 kB
Anonymous:           552 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me ac sd
c000200000-c025800000 rw-p 00000000 00:00 0
Size:             612352 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    1
VmFlags: rd wr mr mw me ac sd hg
c025800000-c025c00000 rw-p 00000000 00:00 0
Size:               4096 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 152 kB
Pss:                 152 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       152 kB
Referenced:          152 kB
Anonymous:           152 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
➜  efficient-go git:(main) ✗ cat /proc/3290226/smaps | grep -A38 c000200000
c000000000-c000200000 rw-p 00000000 00:00 0
Size:               2048 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 556 kB
Pss:                 556 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       556 kB
Referenced:          556 kB
Anonymous:           556 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me ac sd
c000200000-c025800000 rw-p 00000000 00:00 0
Size:             612352 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    1
VmFlags: rd wr mr mw me ac sd hg
c025800000-c025c00000 rw-p 00000000 00:00 0
Size:               4096 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 184 kB
Pss:                 184 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       184 kB
Referenced:          184 kB
Anonymous:           184 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
 cat /proc/3290226/smaps | grep -A38 c000200000
c000000000-c000200000 rw-p 00000000 00:00 0
Size:               2048 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                1568 kB
Pss:                1568 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      1568 kB
Referenced:         1548 kB
Anonymous:          1568 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me ac sd
c000200000-c025800000 rw-p 00000000 00:00 0
Size:             612352 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              612352 kB
Pss:              612352 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    612352 kB
Referenced:       612352 kB
Anonymous:        612352 kB
LazyFree:              0 kB
AnonHugePages:    612352 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    1
VmFlags: rd wr mr mw me ac sd hg
c025800000-c025c00000 rw-p 00000000 00:00 0
Size:               4096 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                1240 kB
Pss:                1240 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      1240 kB
Referenced:         1204 kB
Anonymous:          1240 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
➜  efficient-go git:(main) ✗ cat /proc/3290226/smaps | grep -A38 c000200000
c000000000-c000200000 rw-p 00000000 00:00 0
Size:               2048 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                1568 kB
Pss:                1568 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      1568 kB
Referenced:         1552 kB
Anonymous:          1568 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me ac sd
c000200000-c025800000 rw-p 00000000 00:00 0
Size:             612352 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    1
VmFlags: rd wr mr mw me ac sd hg
c025800000-c025c00000 rw-p 00000000 00:00 0
Size:               4096 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                  60 kB
Pss:                  60 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:        60 kB
Referenced:           56 kB
Anonymous:            60 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB

*/
