package metrics

import (
	"context"
	"net/http"
	"runtime"
	"runtime/pprof"
	"testing"

	"github.com/efficientgo/tools/core/pkg/testutil"
	"github.com/efficientgo/tools/performance/pkg/profiles"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

func ExampleCPUTimeMetric() {
	reg := prometheus.NewRegistry()
	reg.MustRegister(collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}))

	go http.ListenAndServe(":8080", promhttp.HandlerFor(reg, promhttp.HandlerOpts{}))

	for i := 0; i < xTimes; i++ {
		err := doOperation()
		// ...
		_ = err
	}

	printPrometheusMetrics(reg)

	// Output:

}

func TestCPUUsage(t *testing.T) {
	reg := prometheus.NewRegistry()
	reg.MustRegister(collectors.NewGoCollector())

	prepare()

	runtime.SetCPUProfileRate(1000000) // https://share.polarsignals.com/50d1b58/
	stopFn, serr := profiles.StartCPU("./pprof", profiles.CPUTypeBuiltIn)
	testutil.Ok(t, serr)

	var err error
	pprof.Do(context.Background(), pprof.Labels("id", "my_operation"), func(ctx context.Context) {
		err = doOperation() // Operation we want to measure and potentially optimize...
	})

	// .https://share.polarsignals.com/3bcc303/
	testutil.Ok(t, stopFn())

	// Handle error...
	if err != nil {
	}

	tearDown()

	printPrometheusMetrics(reg)

	// Output:
	// initializing operation!
	// doing stuff!
	// closing operation!
	// # HELP go_gc_cycles_automatic_gc_cycles_total Count of completed GC cycles generated by the Go runtime.
	// # TYPE go_gc_cycles_automatic_gc_cycles_total counter
	// go_gc_cycles_automatic_gc_cycles_total 0
	// # HELP go_gc_cycles_forced_gc_cycles_total Count of completed GC cycles forced by the application.
	// # TYPE go_gc_cycles_forced_gc_cycles_total counter
	// go_gc_cycles_forced_gc_cycles_total 0
	// # HELP go_gc_cycles_total_gc_cycles_total Count of all completed GC cycles.
	// # TYPE go_gc_cycles_total_gc_cycles_total counter
	// go_gc_cycles_total_gc_cycles_total 0
	// # HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
	// # TYPE go_gc_duration_seconds summary
	// go_gc_duration_seconds{quantile="0"} 0
	// go_gc_duration_seconds{quantile="0.25"} 0
	// go_gc_duration_seconds{quantile="0.5"} 0
	// go_gc_duration_seconds{quantile="0.75"} 0
	// go_gc_duration_seconds{quantile="1"} 0
	// go_gc_duration_seconds_sum 0
	// go_gc_duration_seconds_count 0
	// # HELP go_gc_heap_allocs_by_size_bytes_total Distribution of heap allocations by approximate size. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
	// # TYPE go_gc_heap_allocs_by_size_bytes_total histogram
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="8.999999999999998"} 3072
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="24.999999999999996"} 7678
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="64.99999999999999"} 9936
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="144.99999999999997"} 11516
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="320.99999999999994"} 12364
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="704.9999999999999"} 12637
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="1536.9999999999998"} 12772
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="3200.9999999999995"} 12840
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="6528.999999999999"} 12884
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="13568.999999999998"} 12916
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="27264.999999999996"} 12918
	// go_gc_heap_allocs_by_size_bytes_total_bucket{le="+Inf"} 12921
	// go_gc_heap_allocs_by_size_bytes_total_sum 1.68584e+06
	// go_gc_heap_allocs_by_size_bytes_total_count 12921
	// # HELP go_gc_heap_allocs_bytes_total Cumulative sum of memory allocated to the heap by the application.
	// # TYPE go_gc_heap_allocs_bytes_total counter
	// go_gc_heap_allocs_bytes_total 1.68584e+06
	// # HELP go_gc_heap_allocs_objects_total Cumulative count of heap allocations triggered by the application. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
	// # TYPE go_gc_heap_allocs_objects_total counter
	// go_gc_heap_allocs_objects_total 12921
	// # HELP go_gc_heap_frees_by_size_bytes_total Distribution of freed heap allocations by approximate size. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
	// # TYPE go_gc_heap_frees_by_size_bytes_total histogram
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="8.999999999999998"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="24.999999999999996"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="64.99999999999999"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="144.99999999999997"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="320.99999999999994"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="704.9999999999999"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="1536.9999999999998"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="3200.9999999999995"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="6528.999999999999"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="13568.999999999998"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="27264.999999999996"} 0
	// go_gc_heap_frees_by_size_bytes_total_bucket{le="+Inf"} 0
	// go_gc_heap_frees_by_size_bytes_total_sum 0
	// go_gc_heap_frees_by_size_bytes_total_count 0
	// # HELP go_gc_heap_frees_bytes_total Cumulative sum of heap memory freed by the garbage collector.
	// # TYPE go_gc_heap_frees_bytes_total counter
	// go_gc_heap_frees_bytes_total 0
	// # HELP go_gc_heap_frees_objects_total Cumulative count of heap allocations whose storage was freed by the garbage collector. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
	// # TYPE go_gc_heap_frees_objects_total counter
	// go_gc_heap_frees_objects_total 0
	// # HELP go_gc_heap_goal_bytes Heap size target for the end of the GC cycle.
	// # TYPE go_gc_heap_goal_bytes gauge
	// go_gc_heap_goal_bytes 4.473924e+06
	// # HELP go_gc_heap_objects_objects Number of objects, live or unswept, occupying heap memory.
	// # TYPE go_gc_heap_objects_objects gauge
	// go_gc_heap_objects_objects 12921
	// # HELP go_gc_heap_tiny_allocs_objects_total Count of small allocations that are packed together into blocks. These allocations are counted separately from other allocations because each individual allocation is not tracked by the runtime, only their block. Each block is already accounted for in allocs-by-size and frees-by-size.
	// # TYPE go_gc_heap_tiny_allocs_objects_total counter
	// go_gc_heap_tiny_allocs_objects_total 0
	// # HELP go_gc_pauses_seconds_total Distribution individual GC-related stop-the-world pause latencies.
	// # TYPE go_gc_pauses_seconds_total histogram
	// go_gc_pauses_seconds_total_bucket{le="-5e-324"} 0
	// go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-10"} 0
	// go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-09"} 0
	// go_gc_pauses_seconds_total_bucket{le="1.2799999999999998e-07"} 0
	// go_gc_pauses_seconds_total_bucket{le="1.2799999999999998e-06"} 0
	// go_gc_pauses_seconds_total_bucket{le="1.6383999999999998e-05"} 0
	// go_gc_pauses_seconds_total_bucket{le="0.00016383999999999998"} 0
	// go_gc_pauses_seconds_total_bucket{le="0.0020971519999999997"} 0
	// go_gc_pauses_seconds_total_bucket{le="0.020971519999999997"} 0
	// go_gc_pauses_seconds_total_bucket{le="0.26843545599999996"} 0
	// go_gc_pauses_seconds_total_bucket{le="+Inf"} 0
	// go_gc_pauses_seconds_total_sum NaN
	// go_gc_pauses_seconds_total_count 0
	// # HELP go_goroutines Number of goroutines that currently exist.
	// # TYPE go_goroutines gauge
	// go_goroutines 4
	// # HELP go_info Information about the Go environment.
	// # TYPE go_info gauge
	// go_info{version="go1.17"} 1
	// # HELP go_memory_classes_heap_free_bytes Memory that is completely free and eligible to be returned to the underlying system, but has not been. This metric is the runtime's estimate of free address space that is backed by physical memory.
	// # TYPE go_memory_classes_heap_free_bytes gauge
	// go_memory_classes_heap_free_bytes 0
	// # HELP go_memory_classes_heap_objects_bytes Memory occupied by live objects and dead objects that have not yet been marked free by the garbage collector.
	// # TYPE go_memory_classes_heap_objects_bytes gauge
	// go_memory_classes_heap_objects_bytes 1.68584e+06
	// # HELP go_memory_classes_heap_released_bytes Memory that is completely free and has been returned to the underlying system. This metric is the runtime's estimate of free address space that is still mapped into the process, but is not backed by physical memory.
	// # TYPE go_memory_classes_heap_released_bytes gauge
	// go_memory_classes_heap_released_bytes 2.162688e+06
	// # HELP go_memory_classes_heap_stacks_bytes Memory allocated from the heap that is reserved for stack space, whether or not it is currently in-use.
	// # TYPE go_memory_classes_heap_stacks_bytes gauge
	// go_memory_classes_heap_stacks_bytes 327680
	// # HELP go_memory_classes_heap_unused_bytes Memory that is reserved for heap objects but is not currently used to hold heap objects.
	// # TYPE go_memory_classes_heap_unused_bytes gauge
	// go_memory_classes_heap_unused_bytes 18096
	// # HELP go_memory_classes_metadata_mcache_free_bytes Memory that is reserved for runtime mcache structures, but not in-use.
	// # TYPE go_memory_classes_metadata_mcache_free_bytes gauge
	// go_memory_classes_metadata_mcache_free_bytes 1984
	// # HELP go_memory_classes_metadata_mcache_inuse_bytes Memory that is occupied by runtime mcache structures that are currently being used.
	// # TYPE go_memory_classes_metadata_mcache_inuse_bytes gauge
	// go_memory_classes_metadata_mcache_inuse_bytes 14400
	// # HELP go_memory_classes_metadata_mspan_free_bytes Memory that is reserved for runtime mspan structures, but not in-use.
	// # TYPE go_memory_classes_metadata_mspan_free_bytes gauge
	// go_memory_classes_metadata_mspan_free_bytes 11480
	// # HELP go_memory_classes_metadata_mspan_inuse_bytes Memory that is occupied by runtime mspan structures that are currently being used.
	// # TYPE go_memory_classes_metadata_mspan_inuse_bytes gauge
	// go_memory_classes_metadata_mspan_inuse_bytes 37672
	// # HELP go_memory_classes_metadata_other_bytes Memory that is reserved for or used to hold runtime metadata.
	// # TYPE go_memory_classes_metadata_other_bytes gauge
	// go_memory_classes_metadata_other_bytes 3.548888e+06
	// # HELP go_memory_classes_os_stacks_bytes Stack memory allocated by the underlying operating system.
	// # TYPE go_memory_classes_os_stacks_bytes gauge
	// go_memory_classes_os_stacks_bytes 0
	// # HELP go_memory_classes_other_bytes Memory used by execution trace buffers, structures for debugging the runtime, finalizer and profiler specials, and more.
	// # TYPE go_memory_classes_other_bytes gauge
	// go_memory_classes_other_bytes 922115
	// # HELP go_memory_classes_profiling_buckets_bytes Memory that is used by the stack trace hash map used for profiling.
	// # TYPE go_memory_classes_profiling_buckets_bytes gauge
	// go_memory_classes_profiling_buckets_bytes 1.444909e+06
	// # HELP go_memory_classes_total_bytes All memory mapped by the Go runtime into the current process as read-write. Note that this does not include memory mapped by code called via cgo or via the syscall package. Sum of all metrics in /memory/classes.
	// # TYPE go_memory_classes_total_bytes gauge
	// go_memory_classes_total_bytes 1.0175752e+07
	// # HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
	// # TYPE go_memstats_alloc_bytes gauge
	// go_memstats_alloc_bytes 1.68584e+06
	// # HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
	// # TYPE go_memstats_alloc_bytes_total counter
	// go_memstats_alloc_bytes_total 1.68584e+06
	// # HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
	// # TYPE go_memstats_buck_hash_sys_bytes gauge
	// go_memstats_buck_hash_sys_bytes 1.444909e+06
	// # HELP go_memstats_frees_total Total number of frees.
	// # TYPE go_memstats_frees_total counter
	// go_memstats_frees_total 0
	// # HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
	// # TYPE go_memstats_gc_cpu_fraction gauge
	// go_memstats_gc_cpu_fraction 0
	// # HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
	// # TYPE go_memstats_gc_sys_bytes gauge
	// go_memstats_gc_sys_bytes 3.548888e+06
	// # HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
	// # TYPE go_memstats_heap_alloc_bytes gauge
	// go_memstats_heap_alloc_bytes 1.68584e+06
	// # HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
	// # TYPE go_memstats_heap_idle_bytes gauge
	// go_memstats_heap_idle_bytes 2.162688e+06
	// # HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
	// # TYPE go_memstats_heap_inuse_bytes gauge
	// go_memstats_heap_inuse_bytes 1.703936e+06
	// # HELP go_memstats_heap_objects Number of allocated objects.
	// # TYPE go_memstats_heap_objects gauge
	// go_memstats_heap_objects 12921
	// # HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
	// # TYPE go_memstats_heap_released_bytes gauge
	// go_memstats_heap_released_bytes 2.162688e+06
	// # HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
	// # TYPE go_memstats_heap_sys_bytes gauge
	// go_memstats_heap_sys_bytes 3.866624e+06
	// # HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
	// # TYPE go_memstats_last_gc_time_seconds gauge
	// go_memstats_last_gc_time_seconds 0
	// # HELP go_memstats_lookups_total Total number of pointer lookups.
	// # TYPE go_memstats_lookups_total counter
	// go_memstats_lookups_total 0
	// # HELP go_memstats_mallocs_total Total number of mallocs.
	// # TYPE go_memstats_mallocs_total counter
	// go_memstats_mallocs_total 12921
	// # HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
	// # TYPE go_memstats_mcache_inuse_bytes gauge
	// go_memstats_mcache_inuse_bytes 14400
	// # HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
	// # TYPE go_memstats_mcache_sys_bytes gauge
	// go_memstats_mcache_sys_bytes 16384
	// # HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
	// # TYPE go_memstats_mspan_inuse_bytes gauge
	// go_memstats_mspan_inuse_bytes 37672
	// # HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
	// # TYPE go_memstats_mspan_sys_bytes gauge
	// go_memstats_mspan_sys_bytes 49152
	// # HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
	// # TYPE go_memstats_next_gc_bytes gauge
	// go_memstats_next_gc_bytes 4.473924e+06
	// # HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
	// # TYPE go_memstats_other_sys_bytes gauge
	// go_memstats_other_sys_bytes 922115
	// # HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
	// # TYPE go_memstats_stack_inuse_bytes gauge
	// go_memstats_stack_inuse_bytes 327680
	// # HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
	// # TYPE go_memstats_stack_sys_bytes gauge
	// go_memstats_stack_sys_bytes 327680
	// # HELP go_memstats_sys_bytes Number of bytes obtained from system.
	// # TYPE go_memstats_sys_bytes gauge
	// go_memstats_sys_bytes 1.0175752e+07
	// # HELP go_sched_goroutines_goroutines Count of live goroutines.
	// # TYPE go_sched_goroutines_goroutines gauge
	// go_sched_goroutines_goroutines 4
	// # HELP go_sched_latencies_seconds Distribution of the time goroutines have spent in the scheduler in a runnable state before actually running.
	// # TYPE go_sched_latencies_seconds histogram
	// go_sched_latencies_seconds_bucket{le="-5e-324"} 0
	// go_sched_latencies_seconds_bucket{le="9.999999999999999e-10"} 3
	// go_sched_latencies_seconds_bucket{le="9.999999999999999e-09"} 3
	// go_sched_latencies_seconds_bucket{le="1.2799999999999998e-07"} 3
	// go_sched_latencies_seconds_bucket{le="1.2799999999999998e-06"} 6
	// go_sched_latencies_seconds_bucket{le="1.6383999999999998e-05"} 9
	// go_sched_latencies_seconds_bucket{le="0.00016383999999999998"} 12
	// go_sched_latencies_seconds_bucket{le="0.0020971519999999997"} 12
	// go_sched_latencies_seconds_bucket{le="0.020971519999999997"} 12
	// go_sched_latencies_seconds_bucket{le="0.26843545599999996"} 12
	// go_sched_latencies_seconds_bucket{le="+Inf"} 12
	// go_sched_latencies_seconds_sum NaN
	// go_sched_latencies_seconds_count 12
	// # HELP go_threads Number of OS threads created.
	// # TYPE go_threads gauge
	// go_threads 7
}
